[package]
name = "http-server"
version = "0.1.0"
edition = "2024"


[dependencies]
anyhow = "1.0.68"                                # error handling
bytes = "1.3.0"                                  # helps manage buffers
thiserror = "2.0.12"                             # error handling
